name: Run Samples
on:
  # By design pull_request_target event run against the version of the workflow in the target branch.
  # So you have to merge changes to this workflow to observe the effects.
  pull_request_target:
    branches:
      - main
    paths:
      - scenarios/**
      - .infra/deployments/**/*.bicep
jobs:
  check-if-external:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: set-environment
        with:
          script: |
            const actionInitiator = context.payload.sender.login;
            const isPublicMember = await github.rest.orgs.checkPublicMembershipForUser({
              org: "Azure-Samples",
              username: actionInitiator
            });
            const isPullRequestEvent = ["pull_request", "pull_request_target"].includes(context.eventName)
            console.log({isPublicMember, isPullRequestEvent})
            if (isPublicMember && isPullRequestEvent) {
              return "external-contribution"
            }
            return ""
          result-encoding: string
  run-samples:
    needs: check-if-external
    runs-on: ubuntu-latest
    # Require manual approval if initiator is not a public member of Azure-Samples
    environment: ${{ needs.check-if-external.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - uses: actions/setup-python@v5
        with:
            python-version: "3.9"
      - name: Install dev dependencies
        run: |
            pip install -r dev-requirements.txt
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy resources
        run: |
            az deployment sub create --location eastus \
              --template-file .infra/deployment/main.bicep \
              --parameters principalType=ServicePrincipal \
              --parameters principalId=${{ secrets.AZURE_CLIENT_ID }} \
              -o json > deployment.json
      - name: Run samples
        run:
            pytest
